class Repopilot < Formula
  desc "Local-first CLI for repository audit and architecture risk detection"
  homepage "https://github.com/MykytaStel/repopilot"
  version "0.0.0"
  license "MIT OR Apache-2.0"

  url "https://github.com/MykytaStel/repopilot"
  sha256 :no_check

  def install
    odie "RepoPilot Homebrew formula is generated by the release workflow. Please install after the next tagged release."
  end

  test do
    system "true"
  end
end